GET http://localhost:3000/products
GET http://localhost:3000/products/99


GET http://localhost:3000/products/category/Electronics


GET http://localhost:3000/products/search?keyword=Torch

GET http://localhost:3000/products/search?keyword=To